# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7585fd0c52d806830b517ac6aef2e9a813ffa797c19c17ca20e07e629ce117b8566934eac3249933066d4b862e6e839e24125af3a77e0474fc1b0b798b6f660f

test:
  secret_key_base: 333173e33dd18a7f2a05233d532a9ebd3c980936c191a87967765e0107dcc225b2f8e15380f7f34923ff7a964a4f829c4d43298bf17772ddf7e70f8276f36fc4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
